### ISSUE TITLE
issue: PHP SDK fetchCard ordering is invalid

### ISSUE THREAD

**Issue by Washkyrie** [tcgdex/documentation#4]
### Where are you having the issue

- [ ] GraphQL
- [ ] JSON API

### Is the issue affecting one of the two elements below ?

- [ ] Translations
- [ ] Definitions Files (Open API, GraphQL Schema, etc)

### Description

Hello,

I try to get all cards from a set with their rarities
With `$set->cards`, we only have CardResume (or CardBrief) object, which doesn't contains rarity.

So I tried `$card= $tcgdex->fetchCard('swsh3', '136');` with set ID and local card ID like in your example (https://tcgdex.dev/rest/set-card) but I got null result.

Do you have advices for me ? Thank you !

**Comment by Aviortheking** [comment]
Thanks for the issue, After looking up at the PHP SDK and the documentation the problem came from the documentation.

you need to use `$card = $tcgdex->fetchCard('136', 'swsh3');` instead of `$card = $tcgdex->fetchCard('swsh3', '136');`, I will be updating the documentation shortly to reflect this error.

**Comment by Aviortheking** [comment]
It was updated on the docs, thanks again for the issue :D

**Comment by Washkyrie** [comment]
Awesome, thank you !
